name: Continuous Integration (CI)

on:
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2
        
      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
               
      - name: Install package dependencies
        with: 
          path: /barber/
          run: npm install
      
      - name: Execute test cases
        run: npm run test
        
      - name: Create test build
        run: npm run build
